-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 15:01:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `login`, `password`, `is_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`offers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `users_login` VARCHAR(45) NOT NULL,
  `users_password` VARCHAR(45) NOT NULL,
  `users_is_admin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `users_login`, `users_password`, `users_is_admin`),
  CONSTRAINT `fk_offers_users1`
    FOREIGN KEY (`users_login` , `users_password` , `users_is_admin`)
    REFERENCES `mydb`.`users` (`login` , `password` , `is_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `offer_id` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `users_login` VARCHAR(45) NOT NULL,
  `users_password` VARCHAR(45) NOT NULL,
  `users_is_admin` VARCHAR(45) NOT NULL,
  `offers_id` INT NOT NULL,
  `offers_user_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `offer_id`, `users_id`, `users_login`, `users_password`, `users_is_admin`, `offers_id`, `offers_user_id`),
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`users_id` , `users_login` , `users_password` , `users_is_admin`)
    REFERENCES `mydb`.`users` (`id` , `login` , `password` , `is_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_offers1`
    FOREIGN KEY (`offers_id` , `offers_user_id`)
    REFERENCES `mydb`.`offers` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
